(define-module (jonabron packages fonts)
  #:use-module (ice-9 regex)
  #:use-module (guix utils)
  #:use-module (guix licenses)
  #:use-module (guix packages)
  #:use-module (guix download)
  #:use-module (guix gexp)
  #:use-module (guix git-download)
  #:use-module (guix build-system font)
  #:use-module (guix build-system gnu)
  #:use-module (guix build-system trivial)
  #:use-module (guix build-system copy)
  #:use-module (gnu packages)
  #:use-module (gnu packages base)
  #:use-module (gnu packages bash)
  #:use-module (gnu packages compression)
  #:use-module (gnu packages fontutils)
  #:use-module (gnu packages gd)
  #:use-module (gnu packages gettext)
  #:use-module (gnu packages glib)
  #:use-module (gnu packages pkg-config)
  #:export (font-bundle-synapsian-karamarea))

(define-public font-bundle-synapsian-karamarea
  (let ((commit "23bd1cf394b1eb1c64f8d8cd575aa676e55f2fec")
        (revision "0"))
    (package
     (name "font-bundle-synapsian-karamarea")
     (version (git-version "1.0" revision commit))
     (source
      (origin
       (uri (git-reference
             (url "https://github.com/nixpup/fonts")
             (commit commit)))
       (method git-fetch)
       (sha256
        (base32 "1yp6nisrs7z2rc6jmr9xr7q1s4q4p7p6ml8cfppgy8z8vzgchxkw"))
       (file-name (git-file-name name version))))
     (outputs '("out" "ttf" "woff"))
     (build-system font-build-system)
     (home-page "https://github.com/nixpup/fonts")
     (synopsis "Font Bundle including Synapsian And Karamarea")
     (description "Font Bundle including the Synapsian Script Font, and the Karamarea Number System Font.")
     (license gpl3))))
