(define-module (jonabron packages fonts)
  #:use-module (ice-9 regex)
  #:use-module (guix utils)
  #:use-module (guix licenses)
  #:use-module (guix packages)
  #:use-module (guix download)
  #:use-module (guix gexp)
  #:use-module (guix git-download)
  #:use-module (guix build-system font)
  #:use-module (guix build-system gnu)
  #:use-module (guix build-system trivial)
  #:use-module (guix build-system copy)
  #:use-module (gnu packages)
  #:use-module (gnu packages base)
  #:use-module (gnu packages bash)
  #:use-module (gnu packages compression)
  #:use-module (gnu packages fontutils)
  #:use-module (gnu packages gd)
  #:use-module (gnu packages gettext)
  #:use-module (gnu packages glib)
  #:use-module (gnu packages pkg-config)
  #:export (font-jonafonts))

(define-public font-jonafonts
  (let ((commit "0a89c6a970802b5fd4a0d9a48f63d86bc97b3268")
        (revision "0"))
    (package
     (name "font-jonafonts")
     (version (git-version "1.0" revision commit))
     (source
      (origin
       (uri (git-reference
             (url "https://github.com/librepup/jonafonts")
             (commit commit)))
       (method git-fetch)
       (sha256
        (base32 "1gslck7nd2cw5bmyh6rsqg40bxxl7mq1xhyjsz1419whaayvrpka"))
       (file-name (git-file-name name version))))
     (outputs '("out"))
     (build-system font-build-system)
     (home-page "https://github.com/librepup/jonafonts")
     (synopsis "Jonafonts Font Bundle")
     (description "Jonafonts Font Bundle Including Nerd Font Symbols, Blex Mono Nerd Font, Synapsian Script, Karamarea Number, TempleOS Font, and much more.")
     (license gpl3))))
